### ISSUE TITLE
Polaris support?

### ISSUE THREAD

**Issue by seesturm** [ROCm-Developer-Tools/rocr_debug_agent#1]
Does the ROCr debug agent support polaris GPUs? Based on the console output it seems not to run
`Warning: Debug Agent: Do not support agent AMD gfx803`

If not supported, is there a chance that support will be added later? Or is there a different package supporting debugging on Polaris?

**Comment by qis-cag** [comment]
Hi, unfortunately the rocr_debug_agent wont be able to support gfx803. The UMR tool may be helpful https://github.com/freedesktop/amd-umr.
