### ISSUE TITLE
Wavefront state not shown for OpenCL kernel

### ISSUE THREAD

**Issue by seesturm** [ROCm-Developer-Tools/rocr_debug_agent#2]
Ok as learned in #1, currently there is no gfx803 support in the rocr_debug_agent. Now I have a gfx900. The warning is gone, but it still does not work. An error is printed, but the "wavefront state" is not shown:

```
$ HSA_TOOLS_LIB=librocr_debug_agent64.so ./launch
[rocr debug agent]: 
Memory access fault at GPU Node: 2
Address: 0x12345xxx (page not present;write access to a read-only page;)
```

Tested with following OpenCL kernel
```
kernel void some(
	global int *rv
) {
	/* Intentionally put illegal address in order to force access fault */
	rv = (global int*) 0x12345678;

	/* some unrelated computations (probably not needed for triggering memory fault) */
	private uchar asdf[16*1024];
	private unsigned i, sum = 0;
	for (i=0; i<sizeof asdf; i++)
		sum += asdf[i];

	/* write result */
	rv[get_global_id(0)] = sum;
}

```

**Comment by seesturm** [comment]
System used
* Vega 56
* ROCm 2.4
* Linux kernel 5.1.0

**Comment by qis-cag** [comment]
Hi, there is a problem in ROCm 2.4 that cause debug agent not able to print the waves upon memory fault. For temporary fix, could you try flip "/sys/module/amdgpu/parameters/noretry" (only for debugging memory fault). Or could try insert "__builtin_trap();" to get the print out if the fault location is known.

**Comment by seesturm** [comment]
Hi @qis-cag . Changed "notretry" from "0" to "1". Still no output is shown.
Also tried "__builtin_trap()". With this register output is shown, but all registers are shown as zero.
```
Queue error state in GPU agent: AMD gfx900
Node: 2
Queue ID: 140423981940736 (Debug trap;)


2 wavefront(s) found in @PC: 0x0000000000000000
printing the first one: 

   EXEC: 0x0000000000000000
 STATUS: 0x00000000
TRAPSTS: 0x00000000
     M0: 0x00000000

     s0: 0x00000000    s1: 0x00000000    s2: 0x00000000    s3: 0x00000000
     s4: 0x00000000    s5: 0x00000000    s6: 0x00000000    s7: 0x00000000
     s8: 0x00000000    s9: 0x00000000   s10: 0x00000000   s11: 0x00000000
    s12: 0x00000000   s13: 0x00000000   s14: 0x00000000   s15: 0x00000000

Lane 0x0
     v0: 0x00000000    v1: 0x00000000    v2: 0x00000000    v3: 0x00000000
Lane ...
```

**Comment by qis-cag** [comment]
Hi @seesturm , sorry your case seems to be a different one. At this point my suggestion would be try the later release. I was also wondering if you could provide your program so we may look into it. Thank you.

**Comment by seesturm** [comment]
I'm using ROCm 2.4 which I assume to be the newest release.
Here are the sources. It is just a dummy example without any gimmicks:
[crash.zip](https://github.com/ROCm-Developer-Tools/rocr_debug_agent/files/3263153/crash.zip)

**Comment by qis-cag** [comment]
Hi @seesturm, sorry for the later response. I think we fixed everything in 2.7. Thanks

**Comment by seesturm** [comment]
Just upgraded to 2.7. Now I'm getting
```
Error: Debug Agent: Cannot preempt queues.
Error: Debug Agent: Cannot preempt queues.
Error: Debug Agent: Cannot preempt queues.
Error: Debug Agent: Cannot preempt queues.
Error: Debug Agent: Cannot preempt queues.
Error: Debug Agent: Cannot preempt queues.
Error: Debug Agent: Interception: Cannot find queue info when destroy.
Segmentation fault (core dumped)
```
This is with kernel 5.2.1

**Comment by qis-cag** [comment]
The error is usually due to mis-match rocr_debug_agent and rocm driver version. Could you check if the binary used is from the corresponding rocm release. Thanks.

**Comment by seesturm** [comment]
According to [ROCm support in upstream Linux kernels](https://github.com/RadeonOpenCompute/ROCm#rocm-support-in-upstream-linux-kernels)

> ... users have the option of ... using the upstream driver and only installing ROCm user-level utilities from AMD's ROCm repositories.

**Comment by qis-cag** [comment]
Yes, however due to the fact debug agent is only loaded by rocm runtime, has no public API, and depends on runtime internal implementation (this make it very hard to check against rocm version). We feel release the binary with each rocm release is OK.

**Comment by seesturm** [comment]
For various reasons I want to keep my kernel up-to-date. The rocm-dkms is already a bit dated and will probably not work with a recent kernel. What a pity that this aspect of the kernel interface is not stable. I guess everything there is to be known was already mentioned. Hence I'm closing this issue.

**Comment by qis-cag** [comment]
Thanks a lot for the feedback. Sorry about the trouble.
