### ISSUE TITLE
Does not compile with -Werror

### ISSUE THREAD

**Issue by haampie** [ROCm-Developer-Tools/rocr_debug_agent#3]
On the 3.7.0 tag, gcc 9.3.0 / hipcc 3.7.0:

```
/tmp/harmen/spack-stage/spack-stage-rocm-debug-agent-3.7.0-tgbobn5pl7jt2hnaoszeskwkxfp4g24v/spack-src/src/code_object.cpp:315:13: error: '<anonymous>' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  315 |     return {};
```

**Comment by lmoriche** [comment]
The fix for this issue will be in the next release:
--- a/src/code_object.cpp
+++ b/src/code_object.cpp
@@ -312,7 +312,7 @@ get_source_file_index (const std::string &file_name)
 
   std::ifstream file (file_name);
   if (!file)
-    return {};
+    return std::nullopt;
 
   auto [it, success]
       = file_map.emplace (file_name, std::vector<std::string>{});

**Comment by xuhuisheng** [comment]
This issue had been resovled finally.
https://github.com/ROCm-Developer-Tools/rocr_debug_agent/commit/97e8d87ed021d2c82103bce29e482204cc8b8eb9

**Comment by qis-cag** [comment]
Closing, since this issue was fixed in newer release.
